server:
  port: 8081
dubbo:
  application:
    name: spring-boot-dubbo-nacos-consumer
  registry:
    address: nacos://192.168.1.13:8848
    protocol: 20880
  protocol:
    name: dubbo
spring:
  datasource:
    url: jdbc:mysql://192.168.1.14:3306/xxl_job?Unicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.163.com
    port: 25
    username: 17335656950@163.com
    password: hjc1314
  application:
    name: springboot_rabbitmq
  rabbitmq:
    host: 192.168.1.13
    port: 5672
    username: ems
    password: ems
    virtual-host: /ems
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml

es:
  hostname: 192.168.1.15
  port: 9300
  scheme: tcp

xxl:
  job:
    admin:
      ### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
      addresses: http://192.168.1.13:8080/xxl-job-admin
    ### xxl-job executor address
    executor:
      appname: vep-job
      ip:
      port: 9888
      ### xxl-job log path
      logpath: /data/applogs/xxl-job/jobhandler
      ### xxl-job log retention days
      logretentiondays: 30
      address:
    ### xxl-job, access token
    accessToken:


